//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JonDJones.Fixtures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JonDJones.Fixtures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online personal wealth awards 2016 - Best stockbroker - Winner.
        /// </summary>
        internal static string Award1AlternateTextDefault {
            get {
                return ResourceManager.GetString("Award1AlternateTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVFN awards 2016 - Best online stockbroker - Winner.
        /// </summary>
        internal static string AwardAlternateTextDefault {
            get {
                return ResourceManager.GetString("AwardAlternateTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our latest awards.
        /// </summary>
        internal static string AwardsLabelDefault {
            get {
                return ResourceManager.GetString("AwardsLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api-dt.development.local.
        /// </summary>
        internal static string DataTableEndPointDomain {
            get {
                return ResourceManager.GetString("DataTableEndPointDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string FacebookLableDefault {
            get {
                return ResourceManager.GetString("FacebookLableDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/pages/The-Share-Centre/173067242723283?ref=hl.
        /// </summary>
        internal static string FacebookLinkDefault {
            get {
                return ResourceManager.GetString("FacebookLinkDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Share Centre Limited is a member of the London Stock Exchange and is authorised and regulated by the Financial Conduct Authority and is entered in the register under reference 146768. Registered office: Oxford House, Oxford Road, Aylesbury, Buckinghamshire, HP21 8SZ. Registered in England no. 2461949. VAT registration no. 596 3918 82..
        /// </summary>
        internal static string FooterTextDefault {
            get {
                return ResourceManager.GetString("FooterTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string HideHubText {
            get {
                return ResourceManager.GetString("HideHubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///  &lt;appender name=&quot;errorFileLogAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot; &gt;
        ///    &lt;!-- Consider moving the log files to a location outside the web application --&gt;
        ///    &lt;file value=&quot;C:\EpiServer10Resources\TheShareCentre\VPP\Logs\EPiServerErrors.log&quot; /&gt;
        ///    &lt;encoding value=&quot;utf-8&quot; /&gt;
        ///    &lt;staticLogFileName value=&quot;true&quot;/&gt;
        ///    &lt;datePattern value=&quot;.yyyyMMdd.&apos;log&apos;&quot; /&gt;
        ///    &lt;rollingStyle value=&quot;Date&quot; /&gt;
        ///    &lt;threshold value=&quot;Error&quot; /&gt;
        ///    &lt;lockingModel type=&quot;log4net.Appender.FileAppender+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Log4NetDefaultConfiguration {
            get {
                return ResourceManager.GetString("Log4NetDefaultConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Share Centre - Simply easier.
        /// </summary>
        internal static string LogoAlternateTextDefault {
            get {
                return ResourceManager.GetString("LogoAlternateTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Share Centre.
        /// </summary>
        internal static string MobileLogoAlternateTextDefault {
            get {
                return ResourceManager.GetString("MobileLogoAlternateTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string MyAccountLabelDefault {
            get {
                return ResourceManager.GetString("MyAccountLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://accounts.development.local/my-summary/.
        /// </summary>
        internal static string MyAccountUrlDefault {
            get {
                return ResourceManager.GetString("MyAccountUrlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an account.
        /// </summary>
        internal static string OpenAccountLabelDefault {
            get {
                return ResourceManager.GetString("OpenAccountLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://accounts.development.local/accounts/.
        /// </summary>
        internal static string OpenAccountUrlDefault {
            get {
                return ResourceManager.GetString("OpenAccountUrlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 class=&quot;h5&quot;&gt;Please remember&lt;/h4&gt;
        ///            &lt;p class=&quot;mb-0&quot;&gt;
        ///                This website does not give personal advice based on your circumstances. It provides information and analysis so you can make your own informed investment decisions. The value of investments can fall as well as rise, and you may get back less than you invested. An investment’s past performance is not a reliable indicator of future performance. Tax allowances and the benefits of tax-efficient accounts could change in the future [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReminderTextDefault {
            get {
                return ResourceManager.GetString("ReminderTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit search.
        /// </summary>
        internal static string ScreenReaderSearchLabelDefault {
            get {
                return ResourceManager.GetString("ScreenReaderSearchLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchLabelDefault {
            get {
                return ResourceManager.GetString("SearchLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchPlaceholderLabelDefault {
            get {
                return ResourceManager.GetString("SearchPlaceholderLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignInLabelDefault {
            get {
                return ResourceManager.GetString("SignInLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://accounts.development.local/login/.
        /// </summary>
        internal static string SignInUrlDefault {
            get {
                return ResourceManager.GetString("SignInUrlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOutLabelDefault {
            get {
                return ResourceManager.GetString("SignOutLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://accounts.development.local/?logout=true.
        /// </summary>
        internal static string SignOutUrlDefault {
            get {
                return ResourceManager.GetString("SignOutUrlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay connected.
        /// </summary>
        internal static string SocialMediaLabelDefault {
            get {
                return ResourceManager.GetString("SocialMediaLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter table.
        /// </summary>
        internal static string TableFeedFilterButtonText {
            get {
                return ResourceManager.GetString("TableFeedFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valued at {{time}} on {{date}} using (at least) 15 minute delayed prices..
        /// </summary>
        internal static string TableFeedFooterText {
            get {
                return ResourceManager.GetString("TableFeedFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valued at {{time}} on {{date}} using (at least) 15 minute delayed prices..
        /// </summary>
        internal static string TableFeedMiniFooterText {
            get {
                return ResourceManager.GetString("TableFeedMiniFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does this table mean?.
        /// </summary>
        internal static string TableFeedMiniTableDetails {
            get {
                return ResourceManager.GetString("TableFeedMiniTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does this table mean?.
        /// </summary>
        internal static string TableFeedTableDetails {
            get {
                return ResourceManager.GetString("TableFeedTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string TwitterLabelDefault {
            get {
                return ResourceManager.GetString("TwitterLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/TheShareCentre.
        /// </summary>
        internal static string TwitterLinkDefault {
            get {
                return ResourceManager.GetString("TwitterLinkDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        internal static string UsefulLinksText {
            get {
                return ResourceManager.GetString("UsefulLinksText", resourceCulture);
            }
        }
    }
}
